-- Baseline migration: captures the live schema as of 2026-09-01.
--
-- This project's schema was hand-authored in the Supabase Dashboard's
-- Table Editor/SQL Editor (see docs/data-model.md) with no migration
-- history before this file. Generated via live SQL introspection
-- (information_schema, pg_policies, pg_get_functiondef, pg_indexes
-- against the linked project) rather than `supabase db pull`/`pg_dump` --
-- this environment has no Docker and no local Postgres client tools, and
-- a `brew install libpq` source build failed (macOS 13, outdated Xcode
-- Command Line Tools).
--
-- This file is registered as already-applied (`supabase migration repair
-- --status applied`) rather than executed, since the tables/policies/
-- functions below already exist live. It exists so future schema changes
-- can be tracked as diffs from here instead of drifting silently the way
-- `collections.share_token`'s default did (see the "share_token's live
-- default drifted" entry in docs/data-model.md).
--
-- NOTE: notes.updated_at is captured here exactly as it exists live --
-- `timestamp without time zone`, nullable, no default -- which is known
-- to be inconsistent with what docs/data-model.md describes
-- (`timestamptz default now()`). That's a tracked follow-up, not fixed
-- in this baseline; see docs/data-model.md.

-- ============================================================
-- Tables
-- ============================================================

create table public.collections (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text,
  share_token uuid,
  created_at timestamptz not null default now()
);

create table public.tags (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text,
  created_at timestamptz not null default now()
);

create table public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title text,
  body text,
  collection_id bigint references public.collections (id) on delete set null,
  image_path text,
  search_vector tsvector generated always as (
    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(body, '')), 'B')
  ) stored,
  created_at timestamptz not null default now(),
  updated_at timestamp without time zone
);

create table public.note_tags (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  note_id bigint not null references public.notes (id) on delete cascade,
  tag_id bigint not null references public.tags (id) on delete cascade,
  created_at timestamptz not null default now()
);

-- ============================================================
-- Indexes (every foreign key column is explicitly indexed --
-- see docs/data-model.md's "Every foreign key column has an
-- explicit index" for why)
-- ============================================================

create index notes_collection_id_idx on public.notes (collection_id);
create index note_tags_note_id_idx on public.note_tags (note_id);
create index note_tags_tag_id_idx on public.note_tags (tag_id);
create index notes_user_id_idx on public.notes (user_id);
create index collections_user_id_idx on public.collections (user_id);
create index tags_user_id_idx on public.tags (user_id);
create index note_tags_user_id_idx on public.note_tags (user_id);
create index notes_search_vector_idx on public.notes using gin (search_vector);

-- ============================================================
-- Row Level Security -- owner-only, per docs/data-model.md
-- ============================================================

alter table public.collections enable row level security;
alter table public.notes enable row level security;
alter table public.tags enable row level security;
alter table public.note_tags enable row level security;

create policy "Users can manage their own collections" on public.collections
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can manage their own notes" on public.notes
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can manage their own tags" on public.tags
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- note_tags needs a stronger check than the other three tables -- see
-- docs/data-model.md's "note_tags needs a stronger check" entry.
create policy "Users can manage their own note_tags" on public.note_tags
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.notes
      where notes.id = note_tags.note_id and notes.user_id = (select auth.uid())
    )
    and exists (
      select 1 from public.tags
      where tags.id = note_tags.tag_id and tags.user_id = (select auth.uid())
    )
  );

-- ============================================================
-- Collection sharing -- SECURITY DEFINER functions, see
-- docs/collection-sharing.md for the full design rationale.
--
-- NOTE: as created, these functions are executable by PUBLIC (Postgres's
-- default grant for functions in an exposed schema), not just the
-- explicit `anon`/`authenticated` grants below -- this is a tracked
-- Medium follow-up (tighten grants / move to a non-exposed schema), not
-- fixed in this baseline. See docs/data-model.md's security-audit
-- follow-ups.
-- ============================================================

create or replace function public.get_shared_collection(p_token uuid)
returns table (id bigint, name text, created_at timestamptz)
language sql
security definer
set search_path = public
as $$
  select id, name, created_at
  from collections
  where share_token = p_token
  limit 1;
$$;

create or replace function public.get_shared_collection_notes(p_token uuid)
returns table (id bigint, title text, body text, created_at timestamptz, updated_at timestamptz)
language sql
security definer
set search_path = public
as $$
  select n.id, n.title, n.body, n.created_at, n.updated_at
  from notes n
  join collections c on c.id = n.collection_id
  where c.share_token = p_token
  order by n.created_at desc;
$$;

grant execute on function public.get_shared_collection (uuid) to anon;
grant execute on function public.get_shared_collection_notes (uuid) to anon;

-- ============================================================
-- Storage -- note-images bucket, see docs/image-uploads.md
-- ============================================================

insert into storage.buckets (id, name, public)
values ('note-images', 'note-images', false)
on conflict (id) do nothing;

create policy "Users can upload their own note images" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'note-images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy "Users can view their own note images" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'note-images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy "Users can delete their own note images" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'note-images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
